// Users

export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";

export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";

export const USER_PROFILE_REQUEST = "USER_PROFILE_REQUEST";
export const USER_PROFILE_SUCCESS = "USER_PROFILE_SUCCESS";
export const USER_PROFILE_FAIL = "USER_PROFILE_FAIL";
export const USER_PROFILE_RESET = "USER_PROFILE_RESET";

export const USER_PROFILE_UPDATE_REQUEST = "USER_PROFILE_UPDATE_REQUEST";
export const USER_PROFILE_UPDATE_SUCCESS = "USER_PROFILE_UPDATE_SUCCESS";
export const USER_PROFILE_UPDATE_FAIL = "USER_PROFILE_UPDATE_FAIL";

export const ADMIN_USERS_LIST_REQUEST = "ADMIN_USERS_LIST_REQUEST";
export const ADMIN_USERS_LIST_SUCCESS = "ADMIN_USERS_LIST_SUCCESS";
export const ADMIN_USERS_LIST_FAIL = "ADMIN_USERS_LIST_FAIL";
export const ADMIN_USERS_LIST_RESET = "ADMIN_USERS_LIST_RESET";

export const USER_DELETE_REQUEST = "USER_DELETE_REQUEST";
export const USER_DELETE_SUCCESS = "USER_DELETE_SUCCESS";
export const USER_DELETE_FAIL = "USER_DELETE_FAIL";

export const ADMIN_UPDATE_USER_REQUEST = "ADMIN_UPDATE_USER_REQUEST";
export const ADMIN_UPDATE_USER_SUCCESS = "ADMIN_UPDATE_USER_SUCCESS";
export const ADMIN_UPDATE_USER_FAIL = "ADMIN_UPDATE_USER_FAIL";
export const ADMIN_UPDATE_USER_RESET = "ADMIN_UPDATE_USER_RESET";

export const USER_LOGOUT = "USER_LOGOUT";

// products

export const PRODUCT_LIST_REQUEST = "PRODUCT_LIST_REQUEST";
export const PRODUCT_LIST_SUCCESS = "PRODUCT_LIST_SUCCESS";
export const PRODUCT_LIST_FAIL = "PRODUCT_LIST_FAIL";

export const PRODUCT_DETAILS_REQUEST = "PRODUCT_DETAILS_REQUEST";
export const PRODUCT_DETAILS_SUCCESS = "PRODUCT_DETAILS_SUCCESS";
export const PRODUCT_DETAILS_FAIL = "PRODUCT_DETAILS_FAIL";

// Orders

export const CART_ADD_PRODUCTS = "CART_ADD_PRODUCTS";
export const CART_REMOVE_PRODUCTS = "CART_REMOVE_PRODUCTS";
export const CART_RESET = "CART_RESET";

export const CART_ADD_PRODUCTS_DESTINATION_REQUEST =
  "CART_ADD_PROD_DEST_REQUEST";
export const CART_ADD_PRODUCTS_DESTINATION_SUCCESS =
  "CART_ADD_PROD_DEST_SUCCESS";
export const CART_ADD_PRODUCTS_DESTINATION_FAIL = "CART_ADD_PROD_DEST_FAIL";

export const CART_ADD_PAYMENT_METHOD = "CART_ADD_PAYMENT_METHOD";

export const ORDER_CREATE_REQUEST = "ORDER_CREATE_REQUEST";
export const ORDER_CREATE_SUCCESS = "ORDER_CREATE_SUCCESS";
export const ORDER_CREATE_FAIL = "ORDER_CREATE_FAIL";

export const ORDER_DETAILS_REQUEST = "ORDER_DETAILS_REQUEST";
export const ORDER_DETAILS_SUCCESS = "ORDER_DETAILS_SUCCESS";
export const ORDER_DETAILS_FAIL = "ORDER_DETAILS_FAIL";

export const ORDER_PAY_REQUEST = "ORDER_PAY_REQUEST";
export const ORDER_PAY_SUCCESS = "ORDER_PAY_SUCCESS";
export const ORDER_PAY_FAIL = "ORDER_PAY_FAIL";
export const ORDER_PAY_RESET = "ORDER_PAY_RESET";

export const LIST_MY_ORDER_REQUEST = "LIST_MY_ORDER_REQUEST";
export const LIST_MY_ORDER_SUCCESS = "LIST_MY_ORDER_SUCCESS";
export const LIST_MY_ORDER_FAIL = "LIST_MY_ORDER_FAIL";
export const LIST_MY_ORDER_RESET = "LIST_MY_ORDER_RESET";
