// Users

export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";

export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";

export const USER_PROFILE_REQUEST = "USER_PROFILE_REQUEST";
export const USER_PROFILE_SUCCESS = "USER_PROFILE_SUCCESS";
export const USER_PROFILE_FAIL = "USER_PROFILE_FAIL";
export const USER_PROFILE_RESET = "USER_PROFILE_RESET";

export const USER_PROFILE_UPDATE_REQUEST = "USER_PROFILE_UPDATE_REQUEST";
export const USER_PROFILE_UPDATE_SUCCESS = "USER_PROFILE_UPDATE_SUCCESS";
export const USER_PROFILE_UPDATE_FAIL = "USER_PROFILE_UPDATE_FAIL";

export const ADMIN_USERS_LIST_REQUEST = "ADMIN_USERS_LIST_REQUEST";
export const ADMIN_USERS_LIST_SUCCESS = "ADMIN_USERS_LIST_SUCCESS";
export const ADMIN_USERS_LIST_FAIL = "ADMIN_USERS_LIST_FAIL";
export const ADMIN_USERS_LIST_RESET = "ADMIN_USERS_LIST_RESET";

export const USER_DELETE_REQUEST = "USER_DELETE_REQUEST";
export const USER_DELETE_SUCCESS = "USER_DELETE_SUCCESS";
export const USER_DELETE_FAIL = "USER_DELETE_FAIL";

export const ADMIN_UPDATE_USER_REQUEST = "ADMIN_UPDATE_USER_REQUEST";
export const ADMIN_UPDATE_USER_SUCCESS = "ADMIN_UPDATE_USER_SUCCESS";
export const ADMIN_UPDATE_USER_FAIL = "ADMIN_UPDATE_USER_FAIL";
export const ADMIN_UPDATE_USER_RESET = "ADMIN_UPDATE_USER_RESET";

export const USER_LOGOUT = "USER_LOGOUT";

// products

export const PRODUCT_LIST_REQUEST = "PRODUCT_LIST_REQUEST";
export const PRODUCT_LIST_SUCCESS = "PRODUCT_LIST_SUCCESS";
export const PRODUCT_LIST_FAIL = "PRODUCT_LIST_FAIL";

export const PRODUCT_DETAILS_REQUEST = "PRODUCT_DETAILS_REQUEST";
export const PRODUCT_DETAILS_SUCCESS = "PRODUCT_DETAILS_SUCCESS";
export const PRODUCT_DETAILS_FAIL = "PRODUCT_DETAILS_FAIL";
export const PRODUCT_DETAILS_RESET = "PRODUCT_DETAILS_RESET";

export const ADMIN_PRODUCT_DELETE_REQUEST = "ADMIN_PRODUCT_DELETE_REQUEST";
export const ADMIN_PRODUCT_DELETE_SUCCESS = "ADMIN_PRODUCT_DELETE_SUCCESS";
export const ADMIN_PRODUCT_DELETE_FAIL = "ADMIN_PRODUCT_DELETE_FAIL";

export const CREATE_PRODUCT_REQUEST = "CREATE_PRODUCT_REQUEST";
export const CREATE_PRODUCT_SUCCESS = "CREATE_PRODUCT_SUCCESS";
export const CREATE_PRODUCT_FAIL = "CREATE_PRODUCT_FAIL";
export const CREATE_PRODUCT_RESET = "CREATE_PRODUCT_RESET";

export const UPDATE_PRODUCT_REQUEST = "UPDATE_PRODUCT_REQUEST";
export const UPDATE_PRODUCT_SUCCESS = "UPDATE_PRODUCT_SUCCESS";
export const UPDATE_PRODUCT_FAIL = "UPDATE_PRODUCT_FAIL";
export const UPDATE_PRODUCT_RESET = "UPDATE_PRODUCT_RESET";

export const CREATE_REVIEW_REQUEST = "CREATE_REVIEW_REQUEST";
export const CREATE_REVIEW_SUCCESS = "CREATE_REVIEW_SUCCESS";
export const CREATE_REVIEW_FAIL = "CREATE_REVIEW_FAIL";
export const CREATE_REVIEW_RESET = "CREATE_REVIEW_RESET";

// Orders

export const CART_ADD_PRODUCTS = "CART_ADD_PRODUCTS";
export const CART_REMOVE_PRODUCTS = "CART_REMOVE_PRODUCTS";
export const CART_RESET = "CART_RESET";

export const CART_ADD_PRODUCTS_DESTINATION_REQUEST =
  "CART_ADD_PROD_DEST_REQUEST";
export const CART_ADD_PRODUCTS_DESTINATION_SUCCESS =
  "CART_ADD_PROD_DEST_SUCCESS";
export const CART_ADD_PRODUCTS_DESTINATION_FAIL = "CART_ADD_PROD_DEST_FAIL";

export const CART_ADD_PAYMENT_METHOD = "CART_ADD_PAYMENT_METHOD";

export const ORDER_CREATE_REQUEST = "ORDER_CREATE_REQUEST";
export const ORDER_CREATE_SUCCESS = "ORDER_CREATE_SUCCESS";
export const ORDER_CREATE_FAIL = "ORDER_CREATE_FAIL";

export const ORDER_DETAILS_REQUEST = "ORDER_DETAILS_REQUEST";
export const ORDER_DETAILS_SUCCESS = "ORDER_DETAILS_SUCCESS";
export const ORDER_DETAILS_FAIL = "ORDER_DETAILS_FAIL";
export const ORDER_DETAILS_RESET = "ORDER_DETAILS_RESET";

export const ORDER_PAY_REQUEST = "ORDER_PAY_REQUEST";
export const ORDER_PAY_SUCCESS = "ORDER_PAY_SUCCESS";
export const ORDER_PAY_FAIL = "ORDER_PAY_FAIL";
export const ORDER_PAY_RESET = "ORDER_PAY_RESET";

export const LIST_MY_ORDER_REQUEST = "LIST_MY_ORDER_REQUEST";
export const LIST_MY_ORDER_SUCCESS = "LIST_MY_ORDER_SUCCESS";
export const LIST_MY_ORDER_FAIL = "LIST_MY_ORDER_FAIL";
export const LIST_MY_ORDER_RESET = "LIST_MY_ORDER_RESET";

export const ADMIN_LIST_ORDERS_REQUEST = "ADMIN_LIST_ORDERS_REQUEST";
export const ADMIN_LIST_ORDERS_SUCCESS = "ADMIN_LIST_ORDERS_SUCCESS";
export const ADMIN_LIST_ORDERS_FAIL = "ADMIN_LIST_ORDERS_FAIL";
export const ADMIN_LIST_ORDERS_RESET = "ADMIN_LIST_ORDERS_RESET";

export const MARK_ORDER_DELIVERED_REQUEST = "MARK_ORDER_DELIVERED_REQUEST";
export const MARK_ORDER_DELIVERED_SUCCESS = "MARK_ORDER_DELIVERED_SUCCESS";
export const MARK_ORDER_DELIVERED_FAIL = "MARK_ORDER_DELIVERED_FAIL";
export const MARK_ORDER_DELIVERED_RESET = "MARK_ORDER_DELIVERED_RESET";

export const ADMIN_FILTER_ORDERS_BY_DATES_REQUEST = "ADMIN_FILTER_ORDERS_BY_DATES_REQUEST";
export const ADMIN_FILTER_ORDERS_BY_DATES_SUCCESS = "ADMIN_FILTER_ORDERS_BY_DATES_SUCCESS";
export const ADMIN_FILTER_ORDERS_BY_DATES_FAIL = "ADMIN_FILTER_ORDERS_BY_DATES_FAIL";

export const ADMIN_FILTER_ORDERS_BY_PAYMENT_METHOD_REQUEST = "ADMIN_FILTER_ORDERS_BY_PAYMENT_METHOD_REQUEST";
export const ADMIN_FILTER_ORDERS_BY_PAYMENT_METHOD_SUCCESS = "ADMIN_FILTER_ORDERS_BY_PAYMENT_METHOD_SUCCESS";
export const ADMIN_FILTER_ORDERS_BY_PAYMENT_METHOD_FAIL = "ADMIN_FILTER_ORDERS_BY_PAYMENT_METHOD_FAIL";

export const ADMIN_FILTER_ORDERS_BY_IS_PAID_REQUEST = "ADMIN_FILTER_ORDERS_BY_IS_PAID_REQUEST";
export const ADMIN_FILTER_ORDERS_BY_IS_PAID_SUCCESS = "ADMIN_FILTER_ORDERS_BY_IS_PAID_SUCCESS";
export const ADMIN_FILTER_ORDERS_BY_IS_PAID_FAIL = "ADMIN_FILTER_ORDERS_BY_IS_PAID_FAIL";

export const ADMIN_FILTER_ORDERS_BY_PROVINCE_REQUEST = "ADMIN_FILTER_ORDERS_BY_PROVINCE_REQUEST";
export const ADMIN_FILTER_ORDERS_BY_PROVINCE_SUCCESS = "ADMIN_FILTER_ORDERS_BY_PROVINCE_SUCCESS";
export const ADMIN_FILTER_ORDERS_BY_PROVINCE_FAIL = "ADMIN_FILTER_ORDERS_BY_PROVINCE_FAIL";

export const ADMIN_GET_ALL_LOANS_REQUEST = "ADMIN_GET_ALL_LOANS_REQUEST";
export const ADMIN_GET_ALL_LOANS_SUCCESS = "ADMIN_GET_ALL_LOANS_SUCCESS";
export const ADMIN_GET_ALL_LOANS_FAIL = "ADMIN_GET_ALL_LOANS_FAIL";

export const ADMIN_LOAN_APPROVE_REQUEST = "ADMIN_LOAN_APPROVE_REQUEST";
export const ADMIN_LOAN_APPROVE_SUCCESS = "ADMIN_LOAN_APPROVE_SUCCESS";
export const ADMIN_LOAN_APPROVE_FAIL = "ADMIN_LOAN_APPROVE_FAIL";

export const ADMIN_GET_LOAN_BY_STATUS_REQUEST = "ADMIN_GET_LOAN_BY_STATUS_REQUEST";
export const ADMIN_GET_LOAN_BY_STATUS_SUCCESS = "ADMIN_GET_LOAN_BY_STATUS_SUCCESS";
export const ADMIN_GET_LOAN_BY_STATUS_FAIL = "ADMIN_GET_LOAN_BY_STATUS_FAIL";